# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["andy.lowry@littlegemexperts.co.uk"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "fastly-url-shortner"
service_id = "tPGpv2OFNA4F2aWIQrMza3"

[local_server]

[scripts]
  build = "cargo build --profile release"

[local_server.kv_stores]
shortner = { file = './test/data/shortner_kv_store.json', format = 'json' }
